# ==========================================
# My-RPC-Framework ????????
# ==========================================

# Zookeeper ??????
rpc.zookeeper.address=127.0.0.1:2181

# ????????
# ???: random (????), roundrobin (????)
rpc.loadbalance.strategy=roundrobin